// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VentanillaUnica.Data;

#nullable disable

namespace VentanillaUnica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429195758_EliminacionMunicipio")]
    partial class EliminacionMunicipio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VentanillaUnica.Models.Ciudadano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ciudadanos");
                });

            modelBuilder.Entity("VentanillaUnica.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("VentanillaUnica.Models.GestionSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaGestion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FuncionarioAnteriorId")
                        .HasColumnType("integer");

                    b.Property<int?>("FuncionarioNuevoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<string>("RealizadoPor")
                        .HasColumnType("text");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioNuevoId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("GestionesSolicitud");
                });

            modelBuilder.Entity("VentanillaUnica.Models.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CiudadanoId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaEstimadaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFinReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroRadicado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int?>("Origen")
                        .HasColumnType("integer");

                    b.Property<int>("TipoTramiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CiudadanoId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("TipoTramiteId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("VentanillaUnica.Models.Tramite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiasEstimados")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tramites");
                });

            modelBuilder.Entity("VentanillaUnica.Models.GestionSolicitud", b =>
                {
                    b.HasOne("VentanillaUnica.Models.Funcionario", "FuncionarioNuevo")
                        .WithMany()
                        .HasForeignKey("FuncionarioNuevoId");

                    b.HasOne("VentanillaUnica.Models.Solicitud", "Solicitud")
                        .WithMany("Gestiones")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuncionarioNuevo");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("VentanillaUnica.Models.Solicitud", b =>
                {
                    b.HasOne("VentanillaUnica.Models.Ciudadano", "Ciudadano")
                        .WithMany("Solicitudes")
                        .HasForeignKey("CiudadanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentanillaUnica.Models.Funcionario", "Funcionario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("FuncionarioId");

                    b.HasOne("VentanillaUnica.Models.Tramite", "TipoTramite")
                        .WithMany("Solicitudes")
                        .HasForeignKey("TipoTramiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudadano");

                    b.Navigation("Funcionario");

                    b.Navigation("TipoTramite");
                });

            modelBuilder.Entity("VentanillaUnica.Models.Ciudadano", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("VentanillaUnica.Models.Funcionario", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("VentanillaUnica.Models.Solicitud", b =>
                {
                    b.Navigation("Gestiones");
                });

            modelBuilder.Entity("VentanillaUnica.Models.Tramite", b =>
                {
                    b.Navigation("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
